export const testData = [
    {
        title: 'Welcome Reception',
        url: [
            '/images/cc1.jpg',
            '/images/cc2.jpg',
            '/images/cc3.jpg',
            '/images/cc4.jpg',
            '/images/cc5.jpg',
            '/images/cc6.jpg',
            '/images/cc7.jpg',
            '/images/cc8.jpg',
            '/images/cc9.jpg',
            '/images/cc10.jpg',
            '/images/cc11.jpeg',
            '/images/cc12.jpg',
            '/images/cc13.jpg',
            '/images/cc14.jpg',
            '/images/cc15.jpeg',
            '/images/cc16.jpg',
        ],
        slug: 'welcome-reception',
        date: 'Jan 12th',
        day: 1
    },
    {
        title: 'Sommelier Standoff',
        url: [
            '/images/cc1.jpg',
            '/images/cc2.jpg',
            '/images/cc3.jpg',
            '/images/cc4.jpg',
            '/images/cc5.jpg',
            '/images/cc6.jpg',
            '/images/cc7.jpg',
            '/images/cc8.jpg',
            '/images/cc9.jpg',
            '/images/cc10.jpg',
            '/images/cc11.jpeg',
            '/images/cc12.jpg',
            '/images/cc13.jpg',
            '/images/cc14.jpg',
            '/images/cc15.jpeg',
            '/images/cc16.jpg',
        ],
        slug: 'sommertier-standoff',
        date: 'Jan 12th',
        day: 1
    },
    {
        title: 'A Taste of Little Spain with Chef Jose Andres',
        url: [
            '/images/cc1.jpg',
            '/images/cc2.jpg',
            '/images/cc3.jpg',
            '/images/cc4.jpg',
            '/images/cc5.jpg',
            '/images/cc6.jpg',
            '/images/cc7.jpg',
            '/images/cc8.jpg',
            '/images/cc9.jpg',
            '/images/cc10.jpg',
            '/images/cc11.jpeg',
            '/images/cc12.jpg',
            '/images/cc13.jpg',
            '/images/cc14.jpg',
            '/images/cc15.jpeg',
            '/images/cc16.jpg',
        ],
        slug: 'a-taste-of-little-spain',
        date: 'Jan 13th',
        day: 2
    },
    {
        title: 'Cocktail Reception with Chefs Kristen Kish & Adrienne Cheatham- Seven Restaurant',
        url: [
            '/images/cc1.jpg',
            '/images/cc2.jpg',
            '/images/cc3.jpg',
            '/images/cc4.jpg',
            '/images/cc5.jpg',
            '/images/cc6.jpg',
            '/images/cc7.jpg',
            '/images/cc8.jpg',
            '/images/cc9.jpg',
            '/images/cc10.jpg',
            '/images/cc11.jpeg',
            '/images/cc12.jpg',
            '/images/cc13.jpg',
            '/images/cc14.jpg',
            '/images/cc15.jpeg',
            '/images/cc16.jpg',
        ],
        slug: 'cocktails-with-chefs-kristen-and-adrienne',
        date: 'Jan 13th',
        day: 2
    },
    {
        title: 'Barefoot BBQ',
        url: [
            '/images/cc1.jpg',
            '/images/cc2.jpg',
            '/images/cc3.jpg',
            '/images/cc4.jpg',
            '/images/cc5.jpg',
            '/images/cc6.jpg',
            '/images/cc7.jpg',
            '/images/cc8.jpg',
            '/images/cc9.jpg',
            '/images/cc10.jpg',
            '/images/cc11.jpeg',
            '/images/cc12.jpg',
            '/images/cc13.jpg',
            '/images/cc14.jpg',
            '/images/cc15.jpeg',
            '/images/cc16.jpg',
        ],
        slug: 'barefoot-bbq',
        date: 'Jan 13th',
        day: 2
    },
    {
        title: 'Stingray City and Rum Point Beach Bash',
        url: [
            '/images/cc1.jpg',
            '/images/cc2.jpg',
            '/images/cc3.jpg',
            '/images/cc4.jpg',
            '/images/cc5.jpg',
            '/images/cc6.jpg',
            '/images/cc7.jpg',
            '/images/cc8.jpg',
            '/images/cc9.jpg',
            '/images/cc10.jpg',
            '/images/cc11.jpeg',
            '/images/cc12.jpg',
            '/images/cc13.jpg',
            '/images/cc14.jpg',
            '/images/cc15.jpeg',
            '/images/cc16.jpg',
        ],
        slug: 'stingray-city',
        date: 'Jan 14th',
        day: 3
    },
    {
        title: 'A Conversation with Eric Ripert',
        url: [
            '/images/cc1.jpg',
            '/images/cc2.jpg',
            '/images/cc3.jpg',
            '/images/cc4.jpg',
            '/images/cc5.jpg',
            '/images/cc6.jpg',
            '/images/cc7.jpg',
            '/images/cc8.jpg',
            '/images/cc9.jpg',
            '/images/cc10.jpg',
            '/images/cc11.jpeg',
            '/images/cc12.jpg',
            '/images/cc13.jpg',
            '/images/cc14.jpg',
            '/images/cc15.jpeg',
            '/images/cc16.jpg',
        ],
        slug: 'a-conversation-with-eric-ripert',
        date: 'Jan 14th',
        day: 3
    },
    {
        title: 'Cocktail reception & dinner at Blue with Chefs Eric Ripert, Dominique Crenn & Tom Colicchio',
        url: [
            '/images/cc1.jpg',
            '/images/cc2.jpg',
            '/images/cc3.jpg',
            '/images/cc4.jpg',
            '/images/cc5.jpg',
            '/images/cc6.jpg',
            '/images/cc7.jpg',
            '/images/cc8.jpg',
            '/images/cc9.jpg',
            '/images/cc10.jpg',
            '/images/cc11.jpeg',
            '/images/cc12.jpg',
            '/images/cc13.jpg',
            '/images/cc14.jpg',
            '/images/cc15.jpeg',
            '/images/cc16.jpg',
        ],
        slug: 'cocktail-reception-and-dinner-at-blue',
        date: 'Jan 14th',
        day: 3
    },
    {
        title: 'Effervescence Party',
        url: [
            '/images/cc1.jpg',
            '/images/cc2.jpg',
            '/images/cc3.jpg',
            '/images/cc4.jpg',
            '/images/cc5.jpg',
            '/images/cc6.jpg',
            '/images/cc7.jpg',
            '/images/cc8.jpg',
            '/images/cc9.jpg',
            '/images/cc10.jpg',
            '/images/cc11.jpeg',
            '/images/cc12.jpg',
            '/images/cc13.jpg',
            '/images/cc14.jpg',
            '/images/cc15.jpeg',
            '/images/cc16.jpg',
        ],
        slug: 'effervescense-party',
        date: 'Jan 14th',
        day: 3
    },
    {
        title: 'Rum and Robusto',
        url: [
            '/images/cc1.jpg',
            '/images/cc2.jpg',
            '/images/cc3.jpg',
            '/images/cc4.jpg',
            '/images/cc5.jpg',
            '/images/cc6.jpg',
            '/images/cc7.jpg',
            '/images/cc8.jpg',
            '/images/cc9.jpg',
            '/images/cc10.jpg',
            '/images/cc11.jpeg',
            '/images/cc12.jpg',
            '/images/cc13.jpg',
            '/images/cc14.jpg',
            '/images/cc15.jpeg',
            '/images/cc16.jpg',
        ],
        slug: 'rum-and-robusto',
        date: 'Jan 15th',
        day: 4
    },
    {
        title: 'Cocktail Reception & Dinner at Agua Restaurant',
        url: [
            '/images/cc1.jpg',
            '/images/cc2.jpg',
            '/images/cc3.jpg',
            '/images/cc4.jpg',
            '/images/cc5.jpg',
            '/images/cc6.jpg',
            '/images/cc7.jpg',
            '/images/cc8.jpg',
            '/images/cc9.jpg',
            '/images/cc10.jpg',
            '/images/cc11.jpeg',
            '/images/cc12.jpg',
            '/images/cc13.jpg',
            '/images/cc14.jpg',
            '/images/cc15.jpeg',
            '/images/cc16.jpg',
        ],
        slug: 'cocktail-reception-and-dinner-at-agua',
        date: 'Jan 15th',
        day: 4
    },
]