import Head from 'next/head'
import React from 'react'

type Props = {}

const auth = (props: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>auth</div>
      </main>
    </>
  )
}

export default auth