import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, { useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { isAuth } from './redux/isAuthSlice'

type Props = {}

const Auth = () => {
	// const Authorization: any = useSelector((state: any) => state.authorization.value)
	// const dispatch = useDispatch()
	const [pw, setPw] = useState('')

	const handleSubmit = (e: any) => {

		e.preventDefault()

		if (pw === '') {
			alert('Yay!')
		} else {
			alert('Ney!')
		}

		// dispatch(isAuth(true))
	}

	return (
		<>
			<Head>
				<title>Deep Blue Images - Sign In</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main className='bg-[url("/images/bg1.webp")] bg-cover relative h-screen w-screen  min-h-screen'>
				<div className="absolute top-0 letf-0 w-full h-full z-10 overflow-hidden">
					<Link href='/' className='text-3xl font-handwritten text-mx-400 text-center pt-4 z-20 w-full flex justify-center'>Deep Blue Images</Link>
					<div className="flex justify-center items-center h-full w-full">

						<form className="p-8 rounded-md bg-mx-200 bg-opacity-80 flex flex-col gap-4 items-center"
							onSubmit={handleSubmit}
						>
							<Image alt='Cayman Cookout Logo' src='/images/cc23logo.webp' width={168} height={65} />
							<i className="ri-lock-line py-4 px-5 bg-mx-100 rounded-full my-2" />
							<p className='text-center'>Enter your password <br />to access your images</p>
							<input
								placeholder='Enter your code...'
								type="text"
								className='outline-none rounded drop-shadow-sm p-2 placeholder:text-mx-200'
								onChange={(e) => setPw(e.target.value)}
							/>
							<button className='px-4 py-2 rounded-md bg-mx-400 text-white'>Access</button>
						</form>
					</div>
				</div>

				<footer className='w-full flex items-center justify-center fixed bottom-4 gap-4 text-mx-400 z-20'>
					<i className="ri-instagram-line hover:text-mx-300" />
					<i className="ri-facebook-line" />
					<i className="ri-youtube-line" />
				</footer>
			</main>
		</>
	)
}

export default Auth