import Head from 'next/head'
import Navigation from './components/Navigation'
import { Space_Grotesk } from '@next/font/google'

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space'
})

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className='bg-slate-500'>
				<Navigation />
			</main>
		</>
	)
}
