import Head from 'next/head'
import Footer from './components/Footer'
import Navigation from './components/Navigation'

export default function Home() {
	return (
		<>
			<Head>
				<title>Deep Blue Images - 2023</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className='bg-mx-300 h-screen w-screen overflow-hidden min-h-screen'>
				<Navigation />
				<Footer />
			</main>
		</>
	)
}
