import Head from 'next/head'
import React from 'react'

const dashboard = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main>
				<h1>Hello</h1>
			</main>
		</>
	)
}

export default dashboard