import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

type Props = {}

const NotAuthorized = (props: Props) => {
    return (
        <>
            <Head>
                <title>Deep Blue Images - Galleries</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>


            <div className='bg-mx-400 min-h-screen text-white relative'>

                <header className='container mx-auto'>
                    <nav className='flex items-center justify-between py-4 border-b-[1px] border-white border-opacity-10'>
                        <Link href='/' className='font-semibold'>Deep Blue Images</Link>
                        <div className="flex gap-2 items-center">
                            <button className='btn3'>Contact</button>
                            <i className="ri-menu-4-line" />
                        </div>
                    </nav>
                </header>

                <main className='container mx-auto'>
                    <section className='flex flex-col justify-center items-center py-12 border-b border-white border-opacity-10'>
                        <h1 className='text-mx-300 font-semibold text-2xl'>You&apos;re not authorized to view this page</h1>
                        <Link href='/' className='pt-6 underline underline-offset-8'>Home</Link>
                    </section>
                </main>

                <footer className='absolute bottom-0 w-full text-center py-4 text-xs'>Deep Blue Images  |  © 2023</footer>
            </div>
        </>
    )
}

export default NotAuthorized